kind: Namespace
apiVersion: v1
metadata:
  name: ml-data-science
  labels:
    app.kubernetes.io/instance: edge-anomaly-detection-hub
    kubernetes.io/metadata.name: ml-data-science
    argocd.argoproj.io/managed-by: edge-anomaly-detection-hub
    modelmesh-enabled: 'true'
    opendatahub.io/dashboard: 'true'
spec:
  finalizers:
    - kubernetes
